# Generated by Django 2.2.4 on 2019-10-04 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20191002_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 18, 39, 52, 307624, tzinfo=utc), verbose_name='key relevance'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveSmallIntegerField(default=18, verbose_name='age'),
        ),
    ]
