# Generated by Django 2.2.4 on 2019-10-04 20:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20191004_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('W', 'W')], max_length=1, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 20, 28, 27, 703516, tzinfo=utc), verbose_name='key relevance'),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='aboutMe',
            field=models.TextField(blank=True, max_length=512, verbose_name='about me'),
        ),
    ]
