# Generated by Django 2.2.4 on 2019-10-06 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20191004_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 8, 13, 4, 32, 377230, tzinfo=utc), verbose_name='key relevance'),
        ),
    ]
