# Generated by Django 2.2.4 on 2019-10-06 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20191006_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='language',
            field=models.CharField(blank=True, max_length=128, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='url_social',
            field=models.CharField(blank=True, max_length=512, verbose_name='url_social'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 8, 17, 48, 9, 564446, tzinfo=utc), verbose_name='key relevance'),
        ),
    ]
